version: '3'

services:
  wb-app:
    build:
      context: .
      target: build-env
    command: ["dotnet", "watch", "--project", "/src/ToDoApi", "run", "--urls", "http://0.0.0.0:80"]
    container_name: dotnet
    env_file: .env.development
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    volumes:
      - ./src:/src
