version: '3'

services:
  wb-app:
    build:
      context: .
    container_name: app
    # entrypoint: ["dotnet", "run"]
    env_file: .env.development
    # expose:
    #   - "80"
    #   - "443"
    ports:
      - 5001:443
      - 5000:80
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
